#!/usr/bin/env bash

# To run, install node and npm, then install jshint:
#   sudo npm install jshint -g

if command -v realpath>/dev/null 2>&1; then
    CURRENT_FILE=`realpath "$0"`
else
    CURRENT_FILE="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/$(basename $0)"
fi
STATIC_ANALYSIS_DIR=`dirname "$CURRENT_FILE"`

if [ "$#" -eq 0 ]; then
    TESTS=package
else
    TESTS="$@"
fi

jshint --config $STATIC_ANALYSIS_DIR/../.jshintrc -e .jsm $TESTS
